
 // Initial version of file, Feb 26
CREATE TABLE STUDENT
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(999) NOT NULL,
    EMAIL VARCHAR(999) NOT NULL,
    SCHOOL_ACCOUNT VARCHAR(999) NOT NULL
);

CREATE TABLE DOCUMENT
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(999) NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATEDBY INT NOT NULL,
    LASTEDITEDBY INT NOT NULL,
    CREATEDAT TIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP NOT NULL
);

// Create FK constraints separately so we can name them to help with debugging later if they are violated

ALTER TABLE DOCUMENT ADD CONSTRAINT FK_DOCUMENT_CREATEDBY
FOREIGN KEY (CREATEDBY) REFERENCES STUDENT(ID);

ALTER TABLE DOCUMENT ADD CONSTRAINT FK_DOCUMENT_EDITEDBY
FOREIGN KEY (LASTEDITEDBY) REFERENCES STUDENT(ID);

